# AutoViaUpdater config
# For understanding difference between dev and normal builds visit here: https://ci.viaversion.com/
# Default builds when enabled are normal builds, but you can explicitly make it dev builds
# All of the builds here are from jenkins, if you want to use any other source use this plugin https://www.spigotmc.org/resources/autoupdateplugins.109683/

ViaVersion:
  # Enable or disable ViaVersion updates (https://ci.viaversion.com/job/ViaVersion)
  enabled: true
  # Enable or disable dev builds. (https://ci.viaversion.com/job/ViaVersion-DEV/)
  # NOTE: Before you enable dev builds, please check when dev builds were last updated in the link, MIGHT be really OUTDATED
  dev: false
  # Enable or disable Java 8 builds (https://ci.viaversion.com/job/ViaVersion-Java8/)
  java8: false

ViaBackwards:
  # Enable or disable ViaBackwards updates (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/)
  enabled: true
  # Enable or disable dev builds. (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/)
  # NOTE: Before you enable dev builds, please check when dev builds were last updated in the link, MIGHT be really OUTDATED
  dev: false
  # Enable or disable Java 8 builds (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Java8/)
  java8: false

ViaRewind:
  # Enable or disable ViaRewind updates (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/)
  enabled: true
  # Enable or disable dev builds. (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-DEV/)
  # NOTE: Before you enable dev builds, please check when dev builds were last updated in the link, MIGHT be really OUTDATED
  dev: false
  # Enable or disable Java 8 builds (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-Java8/)
  java8: false

ViaRewind-Legacy:
  # Enable or disable ViaRewind-Legacy updates. Note: Will not do anything for Bungeecord servers. (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind%20Legacy%20Support/)
  enabled: true
  # Enable or disable dev builds. (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind%20Legacy%20Support-DEV/)
  # NOTE: Before you enable dev builds, please check when dev builds were last updated in the link, MIGHT be really OUTDATED
  dev: false
